### ISSUE TITLE
打印的图片是乱码

### ISSUE THREAD

**Issue by lcz1688** [dongyonghui/BluetoothPrinter#3]
楼主.我用你的demo链接的蓝牙打印机打印出来的二维码和条形码都是乱码.要怎么解决

**Comment by lcz1688** [comment]
> 

- 

1. 

- [ ] @

**Comment by dongyonghui** [comment]
可能和打印机的ESC命令解析有关；
需要查看具体打印机支持的条码ESC命令，替换根据模板转成的ESC条码命令
