### ISSUE TITLE
能与UsbPrinter一起用吗

### ISSUE THREAD

**Issue by qiaoyangyang** [dongyonghui/BluetoothPrinter#4]
与[UsbPrinter](https://github.com/dongyonghui/UsbPrinter)一起用，有冲突

**Comment by qiaoyangyang** [comment]
报：More than one file was found with OS independent path 'org/apache/velocity/tools/view/servlet/velocity.properties'

**Comment by dongyonghui** [comment]
目前不能，USB和蓝牙的二选一；如需合并可以下载源码手动合并，因为两个类库用了部分相同的公用代码和jar包

后期我会新建一个项目，把两个项目合并一下，如需要可以关注后期动态

**Comment by dongyonghui** [comment]
已经发布蓝牙/USB混用的版本，项目地址：https://github.com/dongyonghui/AndroidPrinter

**Comment by qiaoyangyang** [comment]
好的，感谢
